version: "2"
services:
    mysql:
      platform: linux/amd64
      restart: always
      image: mysql:5.6
      container_name: small-scheduler-db
      volumes:
        - ./mysql:/var/lib/mysql
        - ./mysql-logs:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - TZ='Europe/Paris'
    mailer:
      platform: linux/amd64
      restart: always
      image: mwader/postfix-relay:latest
      container_name: small-scheduler-mailer
      environment:
        - POSTFIX_myhostname=small-scheduler.com
    webserver:
      restart: always
      image: nginx:alpine
      container_name: small-scheduler-www
      working_dir: /server
      volumes:
        - ./server:/server
        - ./webapp:/webapp
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx-logs:/var/log/nginx
      ports:
        - "80:80"
        - "8080:8080"
    message-broker:
      restart: always
      image: rabbitmq:3.7-management
      container_name: small-scheduler-message-broker
      ports:
        - 15672:15672
        - 5672:5672
    php-fpm:
      restart: always
      build: php-fpm
      container_name: small-scheduler-php
      working_dir: /server
      volumes:
        - ./server:/server
