version: "2"
services:
    mysql:
      image: mysql:5.6
      container_name: small-scheduler-db
      volumes:
        - ./mysql:/var/lib/mysql
        - ./mysql-logs:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - TZ='Europe/Paris'
      ports:
        - 3306:3306
    mailer:
      image: mwader/postfix-relay:latest
      container_name: small-scheduler-mailer
      environment:
        - POSTFIX_myhostname=small-scheduler.com
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: small-scheduler-phpmyadmin
      environment:
        - PMA_HOST=small-scheduler-db
      ports:
        - "8081:80"
    webserver:
      image: nginx:alpine
      container_name: small-scheduler-www
      working_dir: /server
      volumes:
        - ./server:/server
        - ./webapp:/webapp
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx-logs:/var/log/nginx
      ports:
        - "80:80"
    message-broker:
      image: rabbitmq:3.7-management
      container_name: small-scheduler-message-broker
      ports:
        - 15672:15672
        - 5672:5672
    php-fpm:
      build: php-fpm
      container_name: small-scheduler-php
      working_dir: /server
      volumes:
        - ./server:/server
        - ./php-fpm/small-scheduler-supervisor.conf:/etc/supervisor/conf.d/small-scheduler-supervisor.conf
    webapp:
      build: angular
      container_name: small-scheduler-webapp
      working_dir: /webapp
      volumes:
        - ./webapp:/webapp
      ports:
        - "4200:4200"
