#!/usr/bin/env bash

# install keys for jwt token
echo "#### Install security for jwt token"
sudo apt-get install openssl
cd ../server
mkdir -p config/jwt
openssl genrsa -out config/jwt/private.pem -aes256 4096
openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
echo "Renter passphrase"
read PASSPHRASE
cp .env.dist .env
cat .env | grep -v JWT_PASSPHRASE > .env.new
rm .env
mv ./.env.new .env
echo "JWT_PASSPHRASE=$PASSPHRASE" >> .env

